//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IFServer.rc
//
#define IDD_IFSERVER_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDB_CAP_WIZ                     131
#define IDD_DIALOG_SELECT_ADAPTORS      133
#define IDD_DIALOG1                     136
#define IDD_DIALOG2                     137
#define IDD_DIALOG3                     139
#define IDD_DIALOG4                     140
#define IDB_BITMAP1                     141
#define IDI_ICON_STARTLIGHT             143
#define IDB_STARTLIGHT                  144
#define IDB_IND_1                       145
#define IDB_IND_2                       146
#define IDB_IND_3                       147
#define IDD_DIALOG5                     148
#define IDD_DIALOG6                     150
#define IDC_BUTTON_STARTENGINE          1000
#define IDC_ADAPTER                     1000
#define IDC_BUTTON_STOPENGINE           1001
#define IDC_BUTTON_SELECTADAPTOR        1002
#define IDC_STATIC_ADAPTOR              1004
#define IDC_DLG_FRAME                   1005
#define IDC_EDIT1                       1005
#define IDC_CAPTION_BAR                 1009
#define IDC_PAGE_TREE                   1010
#define IDC_PHELP                       1011
#define IDC_COMBO1                      1012
#define IDC_SHOCKWAVEFLASH1             1013
#define IDC_PROGRESS1                   1014
#define IDC_SHOCKWAVEFLASH2             1014
#define IDC_LIST_IDSRULES               1015
#define IDC_SCROLLBAR1                  1016
#define IDC_SCROLLBAR5                  1017
#define IDC_CHECK3                      1019
#define IDC_SPIN1                       1021
#define IDC_IPADDRESS1                  1022
#define IDC_CHECK5                      1023
#define IDC_STATIC_IDS                  1024
#define IDC_LIST2                       1025
#define IDC_BUTTON1                     1026
#define IDC_LIST3                       1027
#define IDC_BUTTON4                     1027
#define IDC_BUTTON2                     1028
#define IDC_BUTTON5                     1028
#define IDC_BUTTON6                     1029
#define IDC_STATIC_ENGINE               1031
#define IDC_RADIO_SNIFFER               1038
#define IDC_RADIO_IDS_ONLY              1039
#define IDC_RADIO_FIREWALL              1040
#define IDC_STATIC_SNIFFER              1041
#define IDC_STATIC_FIREWALL             1042
#define IDC_EDIT2                       1043
#define IDC_RADIO_START_ENGINE          1043
#define IDC_SPIN2                       1044
#define IDC_RADIO_STOP_ENGINE           1044
#define IDC_EDIT3                       1045
#define IDC_SPIN3                       1046
#define IDC_EDIT4                       1047
#define IDC_SPIN4                       1048
#define IDC_EDIT5                       1049
#define IDC_SPIN5                       1050
#define IDC_EDIT6                       1051
#define IDC_SPIN6                       1052
#define IDC_EDIT7                       1053
#define IDC_SPIN7                       1054
#define IDC_EDIT8                       1055
#define IDC_SPIN8                       1056
#define IDC_EDIT9                       1057
#define IDC_SPIN9                       1058
#define IDC_EDIT10                      1059
#define IDC_SPIN10                      1060
#define IDC_EDIT11                      1061
#define IDC_SPIN11                      1062
#define IDC_EDIT12                      1063
#define IDC_SPIN12                      1064
#define IDC_EDIT13                      1065
#define IDC_SPIN13                      1066
#define IDC_EDIT14                      1067
#define IDC_SPIN14                      1068
#define IDC_EDIT15                      1069
#define IDC_SPIN15                      1070
#define IDC_EDIT16                      1071
#define IDC_SPIN16                      1072
#define IDC_EDIT17                      1073
#define IDC_SPIN17                      1074
#define IDC_EDIT18                      1075
#define IDC_SPIN18                      1076
#define IDC_EDIT19                      1077
#define IDC_SPIN19                      1078
#define IDC_EDIT20                      1079
#define IDC_SPIN20                      1080
#define IDC_STATIC_DIR                  1082
#define IDC_STATIC_DIRECTORY            1083
#define IDC_STATIC_RULES_DIR            1084
#define IDC_STATIC_ENGINE_CONTROL       1084
#define IDC_STATIC_RULES_DIRECTORY      1085
#define IDC_STATIC_SELECT_ADAPTER       1085
#define IDC_STATIC_RULES_FILE           1086
#define IDC_BUTTON_SELECT_ADAPTER       1086
#define IDC_STATIC_RULE_FILE            1087
#define IDC_STATIC_PROGRESS_STATUS      1087
#define IDC_STATIC_ALERTSTAT            1088
#define IDC_STATIC_DENY_LIST_FILE       1088
#define IDC_STATIC_DUMPSTAT             1089
#define IDC_STATIC_DENY_LIST            1089
#define IDC_LIST_ALERTS                 1090
#define IDC_STATIC_ADAPTER_NAME         1091
#define IDC_BUTTON3                     1092
#define IDC_BUTTON8                     1094
#define IDC_BUTTON9                     1095
#define IDC_STATIC_INDI_1               1124
#define IDC_STATIC_INDI_2               1135
#define IDC_STATIC_INDI_3               1136
#define IDC_STATIC_INDI_4               1137
#define IDC_STATIC_INDI_5               1138
#define IDC_STATIC_INDI_6               1139
#define IDC_STATIC_INDI_7               1140
#define IDC_STATIC_INDI_8               1141
#define IDC_STATIC_INDI_9               1142
#define IDC_STATIC_INDI_10              1143
#define IDC_STATIC_INDI_11              1144
#define IDC_STATIC_INDI_12              1145
#define IDC_STATIC_INDI_13              1146
#define IDC_STATIC_INDI_14              1147
#define IDC_STATIC_INDI_15              1148
#define IDC_LIST1                       3109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
